<?php

/**
 * Transport - Conatct on every page
 *
 * @package transport
 * @subpackage transport.inc.options.field
 * @since transport 1.0
 */
return array(
        array(
        'id' => 'email_label_text',
        'label' => __('Email Label Text', 'transport'),
        'desc' => __('Email Label Text', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
        'rows' => '',
        'post_type' => '',
        'taxonomy' => '',
        'min_max_step' => '',
        'class' => '',
        'condition' => '',
        'operator' => 'and'   
    ),
    array(
        'id' => 'transport_email',
        'label' => __('Eamil', 'transport'),
        'desc' => __('Enter email here.', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
        'rows' => '',
        'post_type' => '',
        'taxonomy' => '',
        'min_max_step' => '',
        'class' => '',
        'condition' => '',
        'operator' => 'and'   
    ),
    array(
        'id' => 'request_quote_label_text',
        'label' => __('Request A Quote Label Text', 'transport'),
        'desc' => __('Request A Quote Label Text', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
        'rows' => '',
        'post_type' => '',
        'taxonomy' => '',
        'min_max_step' => '',
        'class' => '',
        'condition' => '',
        'operator' => 'and'   
    ),
    array(
        'id' => 'request_quote_page',
        'label' => __('Request A Quote Page', 'transport'),
        'desc' => __('Select A Quote Page', 'transport'),
        'std' => '',
        'type' => 'custom-post-type-select',
        'section' => 'transport_contact_section',
        'rows' => '',
        'post_type' => 'page',
        'taxonomy' => '',
        'min_max_step' => '',
        'class' => '',
        'condition' => '',
        'operator' => 'and'   
    ),
    array(
        'id' => 'phone_no_label',
        'label' => __('Phone No Label Text', 'transport'),
        'desc' => __('Phone No Label Text', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
        'rows' => '',
        'post_type' => '',
        'taxonomy' => '',
        'min_max_step' => '',
        'class' => '',
        'condition' => '',
        'operator' => 'and'   
    ),
    array(
        'id' => 'phone_no',
        'label' => __('Phone No', 'transport'),
        'desc' => __('Phone No', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
        'rows' => '',
        'post_type' => '',
        'taxonomy' => '',
        'min_max_step' => '',
        'class' => '',
        'condition' => '',
        'operator' => 'and'   
    ),
    array(
        'id' => 'available_time',
        'label' => __('Available Time.', 'transport'),
        'desc' => __('available Time.', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
        'rows' => '',
        'post_type' => '',
        'taxonomy' => '',
        'min_max_step' => '',
        'class' => '',
        'condition' => '',
        'operator' => 'and'   
    ),
array(
        'id' => 'transport_latitude',
        'label' => __('Map Latitude', 'transport'),
        'desc' => __('Map Latitude', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
        'rows' => '',
        'post_type' => '',
        'taxonomy' => '',
        'min_max_step' => '',
        'class' => '',
        'condition' => '',
        'operator' => 'and'   
    ),
    array(
        'id' => 'transport_longitude',
        'label' => __('Map Longitude', 'transport'),
        'desc' => __('Map Longitude', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
        'rows' => '',
        'post_type' => '',
        'taxonomy' => '',
        'min_max_step' => '',
        'class' => '',
        'condition' => '',
        'operator' => 'and'   
    ),
    array(
        'id' => 'transport_query_section_enable',
        'label' => __('Query Section Enable', 'transport'),
        'desc' => __('Query Section Enable/Disable', 'transport'),
        'std' => '',
        'type' => 'on_off',
        'section' => 'transport_contact_section',
        'rows' => '',
        'post_type' => '',
        'taxonomy' => '',
        'min_max_step' => '',
        'class' => '',
        'condition' => '',
        'operator' => 'and'
    ),
    array(
        'id' => 'transport_query_button_label',
        'label' => __('Query Section Button Label.', 'transport'),
        'desc' => __('Query Section Button Label', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
    ),
    array(
        'id' => 'transport_query_button_link',
        'label' => __('Query Section Button Link.', 'transport'),
        'desc' => __('Query Section Button Link', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
    ),
    array(
        'id' => 'transport_query_title',
        'label' => __('Query Section Title', 'transport'),
        'desc' => __('Query Section Title', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section',
    ),
    array(
        'id' => 'transport_query_description',
        'label' => __('Query Section Description', 'transport'),
        'desc' => __('Query Section Description', 'transport'),
        'std' => '',
        'type' => 'text',
        'section' => 'transport_contact_section', 
    ),
    
);
